/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fabian.kotlin.com.cp1



fun Primatest(
    x : Int, i: Int = 2
) :
        Boolean {
    if (x < 2)
        return false
    if (x == 2 || x == 3)
        return true
    if (x % i == 0)
        return false
    if (i + i > x)
        return true
    return Primatest(x,i + 1)
}
 fun main() {
     println("input Bilangan:")
     val prime = readLine()!!.toInt()
     repeat(prime) {
         val x = readLine()!!.toInt()
         val result = if (Primatest(x)) "Is Prime Number"
         else "Is Not Prime Number"
         println("Case #${it+1}: $result")
     }

}




